### ISSUE TITLE
Some clarity on rate limiting.

### ISSUE THREAD

**Issue by AyushExel** [cohere-ai/cohere-python#325]
Hey great job on the multi-lingual models. I've been trying the cohere trial api and I have a question about rate-limiting.
The error says that the number of requests is rate limited to 10/min. But I'm getting these errors even after 4-5 requests (these are batched requests). So I was wondering if the rate-limit also applied at token level like openAI api?

**Comment by samuelpath** [comment]
Hi @AyushExel, I'm not sure this is the best place to ask your question since it is not really related to Python's SDK per se (the API key is language agnostic and can also be used with Node, Go, Curl, Cohere's CLI, and so on).

You would stand a better chance to get a prompt answer by asking your question on [Cohere's Discord community](https://discord.gg/co-mmunity), in the [#general-chat](https://discord.com/channels/954421988141711382/954421988783444043) channel.
